import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" w-full h-5 bg-red-900  mx-auto">
         <Link className="mx-5 " href='/Article'>Article</Link>
         <Link className="mx-5 " href='/Posts'>Posts</Link>
         <Link  className="mx-5 "href='/'>Home</Link>
        </nav>
        {children}
        </body>
    </html>
  );
}
